// swift-tools-version:6.0
import PackageDescription

let package = Package(
    name: "nat",
    platforms: [
        .macOS(.v15)
    ],
    products: [
        .library(name: "NatKit", targets: ["NatKit"]),
        // The product is the app's public name — gnat, graphical nat — so the
        // binary, and with it the dev run's menu bar and dock label, carry it;
        // the target keeps its internal name.
        .executable(name: "gnat", targets: ["NatApp"])
    ],
    dependencies: [
        .package(url: "https://github.com/migueldeicaza/SwiftTerm", from: "1.20.0"),
        // In-app update checks (Updater.swift) — a dependency of NatApp
        // alone, so NatKit stays Sparkle-free.
        .package(url: "https://github.com/sparkle-project/Sparkle", from: "2.8.0")
    ],
    targets: [
        .target(
            name: "NatKit",
            dependencies: [],
            path: "Sources/NatKit",
            resources: [
                // JetBrains Mono — the face every monospaced surface and
                // every text input is set in, shipped rather than asked of
                // the Mac (MonoFont registers it with CoreText at launch).
                // `.copy` rather than `.process`, so the directory survives
                // and the OFL licence beside the four faces ships with them.
                .copy("Resources/Fonts")
            ]
        ),
        .testTarget(
            name: "NatKitTests",
            dependencies: ["NatKit"],
            path: "Tests/NatKitTests"
        ),
        .executableTarget(
            name: "NatApp",
            dependencies: [
                "NatKit",
                .product(name: "SwiftTerm", package: "SwiftTerm"),
                .product(name: "Sparkle", package: "Sparkle")
            ],
            path: "Sources/NatApp",
            resources: [
                // The gnat icon, generated by Scripts/make-icon.sh — carried
                // as a resource so the bare executable `make run` starts can
                // put it on the dock, where a bundled app reads it from
                // Info.plist instead.
                .copy("Resources/AppIcon.icns")
            ],
            // So the bundled app finds Sparkle.framework, copied into
            // Contents/Frameworks by make-app.sh, at runtime.
            linkerSettings: [
                .unsafeFlags(["-Xlinker", "-rpath", "-Xlinker", "@executable_path/../Frameworks"])
            ]
        )
    ]
)
