// swift-tools-version:6.0
import PackageDescription

let package = Package(
    name: "nat",
    platforms: [
        .macOS(.v15)
    ],
    products: [
        .library(name: "NatKit", targets: ["NatKit"]),
        // The product is the app's public name — gnat, graphical nat — so the
        // binary, and with it the dev run's menu bar and dock label, carry it;
        // the target keeps its internal name.
        .executable(name: "gnat", targets: ["NatApp"])
    ],
    dependencies: [
        .package(url: "https://github.com/migueldeicaza/SwiftTerm", from: "1.20.0")
    ],
    targets: [
        .target(
            name: "NatKit",
            dependencies: [],
            path: "Sources/NatKit"
        ),
        .testTarget(
            name: "NatKitTests",
            dependencies: ["NatKit"],
            path: "Tests/NatKitTests"
        ),
        .executableTarget(
            name: "NatApp",
            dependencies: [
                "NatKit",
                .product(name: "SwiftTerm", package: "SwiftTerm")
            ],
            path: "Sources/NatApp",
            resources: [
                // The gnat icon, generated by Scripts/make-icon.sh — carried
                // as a resource so the bare executable `make run` starts can
                // put it on the dock, where a bundled app reads it from
                // Info.plist instead.
                .copy("Resources/AppIcon.icns")
            ]
        )
    ]
)
