#!/bin/bash

set -e

# Navigate to the macos directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$SCRIPT_DIR"

PACKAGE_PATH="$SCRIPT_DIR"
BUILD_DIR="$SCRIPT_DIR/.build"
RELEASE_DIR="$BUILD_DIR/release"
# gnat — graphical nat — is the app's name everywhere a user sees one: the
# product (and so the binary), the bundle, and the Info.plist names below.
PRODUCT_NAME="gnat"
APP_NAME="gnat"
APP_BUNDLE="$BUILD_DIR/$APP_NAME.app"
EXECUTABLE_PATH="$APP_BUNDLE/Contents/MacOS/$APP_NAME"

echo "Building release binary..."
swift build -c release --package-path "$SCRIPT_DIR"

echo "Creating macOS app bundle..."
rm -rf "$APP_BUNDLE"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"

# Copy the executable
cp "$RELEASE_DIR/$PRODUCT_NAME" "$EXECUTABLE_PATH"
chmod +x "$EXECUTABLE_PATH"

# The app's own nat, built from this same checkout so the two are never out
# of step, universal so one bundle serves every Mac. It sits beside the gnat
# executable, which is where PathBootstrap looks for it — the front of the
# PATH the app composes at startup, carried into the agent sessions too.
echo "Building nat (universal) into the bundle..."
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
NAT_STAGING="$BUILD_DIR/nat-universal"
mkdir -p "$NAT_STAGING"
(cd "$REPO_ROOT" && GOOS=darwin GOARCH=arm64 go build -o "$NAT_STAGING/nat-arm64" .)
(cd "$REPO_ROOT" && GOOS=darwin GOARCH=amd64 go build -o "$NAT_STAGING/nat-amd64" .)
lipo -create -output "$APP_BUNDLE/Contents/MacOS/nat" \
    "$NAT_STAGING/nat-arm64" "$NAT_STAGING/nat-amd64"

# The app icon, generated by make-icon.sh and committed
cp "$SCRIPT_DIR/Sources/NatApp/Resources/AppIcon.icns" "$APP_BUNDLE/Contents/Resources/AppIcon.icns"

# The SwiftPM resource bundle (the icon again, for the dev-run code path) —
# copied so any Bundle.module lookup finds it in the bundled app too.
if [ -d "$RELEASE_DIR/nat_NatApp.bundle" ]; then
    cp -R "$RELEASE_DIR/nat_NatApp.bundle" "$APP_BUNDLE/Contents/Resources/"
fi

# Create minimal Info.plist
cat > "$APP_BUNDLE/Contents/Info.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>gnat</string>
	<key>CFBundleIconFile</key>
	<string>AppIcon</string>
	<key>CFBundleIdentifier</key>
	<string>com.craigmjohnston.nat.NatApp</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>gnat</string>
	<key>CFBundleDisplayName</key>
	<string>gnat</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSHighResolutionCapable</key>
	<true/>
	<key>LSMinimumSystemVersion</key>
	<string>15.0</string>
	<key>LSUIElement</key>
	<false/>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright 2025 Craig Johnston</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
</dict>
</plist>
EOF

echo "✓ App bundle created at $APP_BUNDLE"
