#!/bin/bash

set -e

# Navigate to the macos directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$SCRIPT_DIR"

PACKAGE_PATH="$SCRIPT_DIR"
BUILD_DIR="$SCRIPT_DIR/.build"
# gnat — graphical nat — is the app's name everywhere a user sees one: the
# product (and so the binary), the bundle, and the Info.plist names below.
PRODUCT_NAME="gnat"
APP_NAME="gnat"
APP_BUNDLE="$BUILD_DIR/$APP_NAME.app"
EXECUTABLE_PATH="$APP_BUNDLE/Contents/MacOS/$APP_NAME"

# The app's own version, carried into the Info.plist below. A release build
# sets both from the workflow's run; a local build with neither set gets the
# version this bundle has always reported.
APP_VERSION="${APP_VERSION:-1.0}"
APP_BUILD="${APP_BUILD:-1}"

echo "Building release binary (arm64)..."
# Apple silicon only: Intel Macs are no longer supported, so neither gnat nor
# the bundled nat below carries an x86_64 slice, and there is nothing to lipo.
# `--show-bin-path` is what locates the products, since that path is a
# SwiftPM implementation detail this must not hardcode.
swift build -c release --package-path "$SCRIPT_DIR" --arch arm64
RELEASE_DIR="$(swift build -c release --package-path "$SCRIPT_DIR" --arch arm64 --show-bin-path)"

echo "Creating macOS app bundle..."
rm -rf "$APP_BUNDLE"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"

# The executable, stripped of its local and debug symbols (well over half its
# size). The unstripped one is kept beside the bundle, named for the version,
# so a crash report from this release can still be symbolicated — the
# release workflow publishes it next to the dmg. Stripping here, before
# release-app.sh signs anything, is what keeps the signature valid: strip
# rewrites the file, and a signature made before it would no longer match.
cp "$RELEASE_DIR/$PRODUCT_NAME" "$BUILD_DIR/$APP_NAME-$APP_VERSION-unstripped"
cp "$RELEASE_DIR/$PRODUCT_NAME" "$EXECUTABLE_PATH"
strip -rSTx "$EXECUTABLE_PATH"
chmod +x "$EXECUTABLE_PATH"

# The app's own nat, built from this same checkout so the two are never out
# of step. It sits beside the gnat executable, which is where PathBootstrap
# looks for it — the front of the PATH the app composes at startup, carried
# into the agent sessions too.
echo "Building nat (arm64) into the bundle..."
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# The same APP_VERSION the Info.plist carries is stamped into nat, so the app
# and the binary it shells out to report one version. `-s -w` drops the
# symbol table and DWARF, a third of the binary; a Go panic's stack trace
# still names every function, since that comes from the runtime's own tables.
NAT_LDFLAGS="-s -w -X github.com/craigmjohnston/nat/internal/version.stamped=$APP_VERSION"
(cd "$REPO_ROOT" && GOOS=darwin GOARCH=arm64 go build -ldflags "$NAT_LDFLAGS" -o "$APP_BUNDLE/Contents/MacOS/nat" .)

# The app icon, generated by make-icon.sh and committed. These are the only
# copies the bundled app ships: Finder reads AppIcon through the plist's
# CFBundleIconFile, and NatApp.iconImage finds both here, in the bundle's
# own Resources. SwiftPM's nat_NatApp.bundle holds nothing but these two
# icns again — for the bare executable `swift run` starts, which has no
# Resources — and nothing reads it through Bundle.module, so it is not
# copied in.
cp "$SCRIPT_DIR/Sources/NatApp/Resources/AppIcon.icns" "$APP_BUNDLE/Contents/Resources/AppIcon.icns"
cp "$SCRIPT_DIR/Sources/NatApp/Resources/AppIconDark.icns" "$APP_BUNDLE/Contents/Resources/AppIconDark.icns"

# NatKit's resource bundle — the three Fira Code faces MonoFont registers
# at launch. Without it the app still runs, in the monospaced system font, so
# this is copied rather than asserted; see MonoFont.resourceBundle, which
# looks here first.
if [ -d "$RELEASE_DIR/nat_NatKit.bundle" ]; then
    cp -R "$RELEASE_DIR/nat_NatKit.bundle" "$APP_BUNDLE/Contents/Resources/"
fi

# Sparkle.framework, from SwiftPM's own binary-target artifact — the same one
# NatApp links against at build time (Package.swift's rpath is what finds it
# here at runtime). The slice path is per-SwiftPM-version; verify it after
# updating Sparkle.
mkdir -p "$APP_BUNDLE/Contents/Frameworks"
cp -R "$BUILD_DIR/artifacts/sparkle/Sparkle/Sparkle.xcframework/macos-arm64_x86_64/Sparkle.framework" \
    "$APP_BUNDLE/Contents/Frameworks/"

# Create minimal Info.plist. The delimiter is unquoted so APP_VERSION/
# APP_BUILD substitute into it below — the body has no $, backtick or
# backslash otherwise, so nothing else in it expands.
cat > "$APP_BUNDLE/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>gnat</string>
	<key>CFBundleIconFile</key>
	<string>AppIcon</string>
	<key>CFBundleIdentifier</key>
	<string>com.craigmjohnston.nat.NatApp</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>gnat</string>
	<key>CFBundleDisplayName</key>
	<string>gnat</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$APP_VERSION</string>
	<key>CFBundleVersion</key>
	<string>$APP_BUILD</string>
	<key>LSHighResolutionCapable</key>
	<true/>
	<key>LSMinimumSystemVersion</key>
	<string>15.0</string>
	<key>LSUIElement</key>
	<false/>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright 2025 Craig Johnston</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>SUFeedURL</key>
	<string>https://github.com/craigmjohnston/nat/releases/latest/download/appcast.xml</string>
	<key>SUPublicEDKey</key>
	<!-- The public half of the EdDSA key generate_keys made; the private
	     half signs each release's appcast in CI. -->
	<string>Nql+xmZdlzTO+jvBm3lJzQIVy8Rkwr8pSJ6MTBGOLBc=</string>
	<key>SUEnableAutomaticChecks</key>
	<true/>
</dict>
</plist>
EOF

echo "✓ App bundle created at $APP_BUNDLE"
